// <auto-generated />
namespace task18_9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddEmailToStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEmailToStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202409180711347_AddEmailToStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
